lib/verdict/assignment.rb, lib/verdict/experiment.rb, test/assignment_test.rb, test/experiment_test.rb
This PR adds a boolean `timestamps_out_of_band` option to `Verdict::Experiment`, to be used as an override in the `Verdict::Assignment` constructor when initializing its `@returning` attribute and `#returning?` method. 
Right now, the `Verdict::Assignment`' [constructor](https://github.com/Shopify/verdict/blob/master/lib/verdict/assignment.rb#L9) is designed to assume that instances created with a non nil `originally_created_at` timestamp are `#returning?` assignments that had been assigned previously and are being fetched. 
Having this option set to true allows us to set the timestamp of an experiment assignment with [experiment#subject_assignment](https://github.com/Shopify/verdict/blob/master/lib/verdict/experiment.rb#L91) when creating it manually, and have it considered to be a newly …
=> Add `timestamps_out_of_band` option to Experiment

.travis.yml
@ohsabry @wvanbergen 
There was an issue in bundler the causes a NoMethodError (spec undefined for nil:NilClass). It looks like recent versions of ruby on travis are ok, but 1.9.3 needs to update bundler before installing (see [this PR](https://github.com/bundler/bundler/pull/3559) for details ~ April 2015).
Tell travis to update bundler before installing. I've also cached bundles for faster CI runs (auto updates if the bundle is updated).
=> Tweaking Travis for Green

lib/verdict/version.rb
Bumping minor version of the gem after adding a new backwards compatible feature in https://github.com/Shopify/verdict/pull/16
Will rebase after @pseudomuto's bundler fix before merging. 
@pseudomuto @wvanbergen
=> bump version to 0.5.0

.travis.yml, CHANGELOG.md, README.md, lib/verdict/assignment.rb, lib/verdict/conversion.rb, lib/verdict/experiment.rb, lib/verdict/storage/base_storage.rb, lib/verdict/tasks.rake, lib/verdict/version.rb, test/assignment_test.rb, test/conversion_test.rb, test/rake_tasks_test.rb
Verdict was implicitly somewhat coupled to key-value stores.
Public methods currently take a `subject_identifier`, instead of a `subject`, which is not ideal when you use an ORM like ActiveRecord. As AR allows you to cache associations, you can make a better use of resources when your storage class takes a `subject`, instead of `subject_identifier`.
This PR changes Verdict's public API to always take a `subject`, instead of a `subject_identifier`.
Existing storages won't break, as they'll still retrieve the `subject_identifier` using `Experiment#subject_identifier(subject)`.
This PR allows us to implement a Verdict Storage similar to this:
```ruby
class SQLStorage < Verdict::Storage::BaseStorage
def store_assignment(assignment)
shop = assignment.subject
raise Verdict::InvalidSubject, …
```
=> Change public methods to take a subject, instead of a subject_identifier

lib/verdict/railtie.rb
Rails [freezes](https://github.com/rails/rails/blob/master/railties/lib/rails/engine.rb#L571) the `config.*_paths` arrays once it starts initializing for sanity. It'd really suck if sometimes code loading worked and sometimes it didn't based on what controllers had been autoloaded already or something like that, so Rails mandates that all changes to the load paths happen during initialization and never after by making the paths impossible to change at a certain during initialization (linked above).
This railtie however reassigns to the config object an entirely new (filtered) Array object that isn't frozen, so now, the eager load paths could be changed at runtime without any issue! 
I think we should maintain Rails' semantics for these objects and freeze this sucker after fiddling with …
=> Ensure that the eagerload paths are re-frozen after being reassigned (as plain old Rails would be)

lib/verdict.rb
Verdict currently holds references to all experiments in
`Verdict.respository`. A common use case for Verdict is to subclass
`Verdict::Experiment` to add your own behaviour. This is problematic
when the subclasses are autoloaded by Rails and can cause Rails to raise
the following exception:
> "ArgumentError: A copy of _Some::Experiment_ has been removed from the
module tree but is still active!"
The fix for this is to provide a mechanism by which we can trigger
Verdict to reload its experiments via an ActiveSupport `to_prepare`
block in `config/environments/development.rb`. This PR adds the
following:
- A new method `Verdict.clear_repository_cache` which nils out the
repository instance variable so the next call to `Verdict[]` will
trigger reloading all experiments. This can be called in …
=> Fix issues related to holding references to autoloaded code

CHANGELOG.md, lib/verdict/railtie.rb
Following up on #25, turns out we can integrate `Verdict.clear_repository_cache` directly in our railtie, so we don't have to ask whoever uses the gem to add it to their env file.
tophatted locally and it works perfectly.
=> Integrate Verdict.clear_repository_cache with our railtie

CHANGELOG.md, lib/verdict/railtie.rb, lib/verdict/version.rb
This PR does two things:
- fixes a bug in Verdict where Verdict.directory is being overwritten
- Uses directory globbing on Verdict.directory, so we can define `Verdict.directory = "#{Rails.root}/whatever/*/app/experiments"`
Thanks to @kirs for pointing out we're overwriting `Verdict.directory` :)
=> Fix Verdict.directory

CHANGELOG.md, lib/verdict/experiment.rb, lib/verdict/version.rb, test/experiment_test.rb
Allow Experiment definitions to
- specify multiple `qualify` blocks
- allow pass of an argument with a method name as a symbol, instead of a block (like AR validations)
=> Multiple qualify blocks

README.md
The missing underscore causes the sample code to break.
While not a big deal, it is a source of distraction/confusion when first setting things up.
=> Add missing underscore

lib/verdict/railtie.rb, test/app/experiments/test_rails_app_experiment.rb, test/assignment_test.rb, test/experiment_test.rb, test/fake_app.rb, test/rake_tasks_test.rb, test/segmenters/static_segmenter_test.rb, test/storage/legacy_redis_storage_test.rb, test/storage/redis_storage_test.rb, test/verdict_rails_test.rb, verdict.gemspec
Addresses issue #43 
Eagerly loads the discovery method within `railtie.rb` within the `config.to_prepare` method which will only have `Verdict.discovery` called once in production at the beginning.
Also added a new `verdict_rails_test.rb` file that tests verdict within a rails application and also added a mock experiement for the fake rails application to load to test.
Top Hating  🎩 : 
Currently I've tested it within the help application and within core as a dependency. 
To run tests be sure to have a redis server running and run `rake test`
=> Eagerly load discovery method

CHANGELOG.md, lib/verdict/experiment.rb
This PR fixes a typo in the default `NotImplementedError` raised by `Experiment.fetch_subject`.
**Before**:
```
NotImplementedError: Fetching subjects based in identifier is not implemented for experiment @{handle.inspect}.
```
**After**:
```
NotImplementedError: Fetching subjects based in identifier is not implemented for experiment "test_experiment".
```
=> Fix typo in Experiment#fetch_subject

CHANGELOG.md, lib/verdict/experiment.rb, lib/verdict/storage/base_storage.rb, lib/verdict/storage/redis_storage.rb, test/experiment_test.rb, test/storage/redis_storage_test.rb
Adds a way to clean up experiments (specifically when you store them in redis). This no-ops for other storage methods that don't require a cleanup step.
=> Add Verdict::Experiment#cleanup

lib/verdict/storage/redis_storage.rb, test/storage/redis_storage_test.rb
This was added to the [previous PR](https://github.com/Shopify/verdict/pull/48) after talking with @shivnagarajan, but it doesn't play well with our distributed redis infrastructure.
=> Don't rename redis experiment key when cleaning up

lib/verdict.rb, lib/verdict/railtie.rb
In core [we call `Verdict.discovery` on boot](https://github.com/Shopify/shopify/blob/261c95e8c24438d0ab8f3bbd4ab1d2cff74ea56d/config/application.rb#L299) because it's a slow operation so we want it to happen during boot rather than of the first request.
The proper pattern for this is to define a `Namespace.eager_load!` method and append `Namespace` into `app.config.eager_load_namespace`.
This way users won't have to know about this, it will happen automatically.
=> Automatically eager load when inside a Rails app

CHANGELOG.md, lib/verdict/storage/base_storage.rb, lib/verdict/storage/redis_storage.rb, test/storage/redis_storage_test.rb
This PR build up on the work that was done in #48 - Change `#cleanup` to take an `experiment`, instead of a `scope`.
This is more consistent with the rest of API (public methods deal with experiments, protected methods deal with scopes and keys).
Also, updated some comments that were probably overlooked when copy-pasted.
=> Storage API - make public API more consistent

README.md
I was exploring extracting the experiment assignments storage to use for data analysis, but then after thinking some more (and reading the README), I realized there are good reasons to separate the operational and analytical data stores. I updated the README to expand on that rationale a bit.
=> Add rationale for why storage shouldn't be used for analysis

.gitignore, CHANGELOG.md, README.md, lib/verdict/experiment.rb, lib/verdict/storage.rb, lib/verdict/storage/cookie_storage.rb, test/experiment_test.rb, test/storage/cookie_storage_test.rb
This PR adds a `CookieStorage` backend, which enables Verdict to store experiment assignments in cookies. 
For the most part this is straightforward with a few things worth highlighting:
- It's expected that applications override `storage.cookies` to an instance of [`ActionDispatch::Cookies`](https://api.rubyonrails.org/v5.2.3/classes/ActionDispatch/Cookies.html). By default the backend is very similar to `MemoryStorage` in that assignments are stored in a hash. It's only when the AD:C (or interfaces that mirror it) is plugged in that cookies are actually set to the browser.
- It introduces a convention that the `name` of experiments/groups is a value that we are happy with a client knowing. Experiments and Group both inherit `Verdict::Metadata` which has this property, but it's a not a …
=> Add CookieStorage backend

CONTRIBUTING.md, README.md, docs/concepts.md
When using this gem for the first time, my team and I struggled to learn the concepts that were involved, especially as we were coming from a "homegrown" solution to A/B testing that didn't use these terms.
To help, I wrote some concept documentation in our project. I thought I'd offer to backport it to the gem considering it's open-source and there may be others that would benefit.
If I've misunderstood anything, or things are wrong, please let me know!
=> Add concepts documentation

CHANGELOG.md, lib/verdict/railtie.rb
Fixes #59 
Before the gem experiments directory was loaded twice (once by the Gem, once by Zeitwerk), raising an error
* We use the new `config.autoloader` method to detect what is the rails autoloader.
* Then we configure Zeitwerk to ignore the experiments folder,
* We safeguard against rails configuration for version older than 6 which didn't had autoloader method.
PS : I didn't bump the gem version, since I'm not an owner.
=> Support Zeitwerk autoloading

.travis.yml
I have triggered a master build at https://travis-ci.org/github/Shopify/verdict/builds/669739330, which is failing because the jruby job is failing. For now, let's allow this job to tail to not block PRs. Later on, we can decide whether to remove the job entirely.
@Shopify/experiments
=> Allow jruby job to fail

lib/verdict/experiment.rb, test/experiment_test.rb
**Background**
We want to support time scheduling in Verdict to enable strict control over **when** the experiment is running. This is important, for instance, to avoid the "different day" bias that arise when an experiment is not stopped at a desired, pre-planned time.
Closes https://github.com/Shopify/verdict/issues/63.
**Changes**
- New (optional) `schedule_start_timestamp` and `schedule_end_timestamp` methods in the Experiment definition. These are used to limit experiment's timeline. It is possible to one, both, or neither of these methods when defining an experiment.
- Call `is_scheduled?` every time, in `switch`, before calling `assign`, to make sure that the experiment is scheduled.
- Unit tests.
@Shopify/experiments
=> Support experiment scheduling time constraint

CHANGELOG.md, lib/verdict/version.rb
Similar to https://github.com/Shopify/verdict/commit/60682ac9b683cc93f2d614b9e93d94bbe2f05487, I've updated the changelog and the version so we can proceed with a release.
=> Prepare for 0.13.0 release

verdict.gemspec
Shipit is failing because the gemspec is missing `allowed_push_host`.
> Can't release the gem: spec.metadata['allowed_push_host'] must be defined.
This PR assigns `allowed_push_host` to rubygems (i.e. the only host we are pushing to).
=> Add allowed_push_host to gemspec

lib/verdict/experiment.rb, test/experiment_test.rb
Step one for this issue: https://github.com/Shopify/experiments/issues/332
Implement the `schedule_stop_analysis_timestamp` and `is_stopped_new_assignments?` method for Verdict experiment.
The reason we want to do this is: Users need to stop the new assignments to the experiment as they could have a "cooldown" period for their experiment analysis. The experiment has not ended yet, the `switch` method will not assign any subject into new groups. 
**Test cases:**
1. test if the `is_stop_new_assignments` flag worked as expected.
2. test if start or end timestamp is missing, `is_stop_new_assignments` wouldn't work as expected.
3. test if an assignment has already occurred, it will still respect `stop_new_assignment` timestamp
cc @Shopify/experiments
=> Add schedule stop new assignment timestamp

lib/verdict/experiment.rb, test/experiment_test.rb
Part of https://github.com/Shopify/experiments/issues/332
As a discussion with @Prabhashishsingh and the design for EXP new dashboard's creation page: https://github.com/Shopify/experiments/issues/292, we want the `start_timestamp`, `end_timestamp` and `stop_new_assignment_timestamp` has the following inclusion and exclusion characteristics:
1. The time interval from `start_timestamp` to `end_timestamp` (aka experiment schedule time period), 
`start_timestamp` should be **included**, but `end_timestamp` should be **excluded**. 
Example:
An Experiment start from `2020-04-01` to `2020-04-30`. From `2020-04-01 12:00 am`, experiment assignment should start, and before `2020-04-30 12:00 am`, experiment assignment should stop.
2. The time interval from `stop_new_assignment_timestamp` to …
=> Handle start, end and stop_new_timestamp's inclusion and exclusion 

CHANGELOG.md, lib/verdict/version.rb
Prerequisite: https://github.com/Shopify/verdict/pull/68 and https://github.com/Shopify/verdict/pull/70
Release the `schedule_stop_new_assignment_timestamp` with verdict `0.14.0`.
cc @Shopify/experiments
=> Prepare release for 0.14.0

lib/verdict/experiment.rb, test/experiment_test.rb
Dev portion of: https://github.com/Shopify/experiments/issues/505
This adds another param to the `switch` method. This `qualifier` param allows the user to pass in custom qualifiers outside of the original experiment definition.
=> Allow qualifiers in switch

lib/verdict/experiment.rb
#72 modified the `subject_qualifies?` method to add another parameter. This parameter was not given a default value, and thus broke for users that were calling this method directly. This PR adds a default value for the method, remedying this issue.
=> Add default for dynamic_qualifiers

.travis.yml
2.0, 2.1, 2.3.3 are very old Ruby versions. This PR changes so that CI runs 2.5, 2.6, 2.7 instead, which I believe is what most apps would be running. Should help https://github.com/Shopify/verdict/pull/76 pass.
=> Bump CI ruby versions - run 2.5, 2.6, 2.7

lib/verdict/experiment.rb, test/experiment_test.rb
Some consumers of Verdict were manually overriding the `subject_qualifies?` method. This led to errors because as of >v0.15.0, the method signature was changed to accept 3 parameters. However, the overrided method definitions only expected 2 parameters. In order to maintain backwards compatibility, an intermediary step was added to determine which version of the `subject_qualifies?` method should be invoked.
=> Add dynamic switcher for subject qualifies

Gemfile, lib/verdict/storage/redis_storage.rb, test/storage/redis_storage_test.rb, test/test_helper.rb, verdict.gemspec
Currently apps are required to pass in a single `Redis` connection object. If the service is using Sidekiq or Puma, it's likely to be using multiple threads, and thus concurrent access to Verdict storage may cause waiting. By allowing the app to pass in a [`ConnectionPool`](https://github.com/mperham/connection_pool) instead, multiple threads can concurrently access the Redis.
=> Allow using a ConnectionPool object for the Redis storage

CHANGELOG.md, lib/verdict/version.rb
To release https://github.com/Shopify/verdict/pull/76.
=> Bump version to v0.16.0

lib/verdict/storage/redis_storage.rb
We have a couple big experiments (+1GB in assigments). Our redis storage is filling up, so we created a task to remove stale experiments. It basically creates a Verdict experiment on the fly for the handle and calls `cleanup` on it.
That's calling `scrub`, which is recursive, and it's throwing `stack level too deep` errors, halting the process. This changes the scrub method to be iterative instead.
=> Make scrub be iterative instead of recursive so it does not throw a stack level too deep error for big experiments

test/storage/cookie_storage_test.rb
We're using an internal Rails class in tests which made our tests break with the release of Rails 6.1.
This PR mocks the request in CookieStorageTest to support this change.
Ideally we should move away from using internal Rails classes but thats for another PR.
=> CookieStorage: Mock request in tests to support changes in Rails 6.1
